core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('user.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path('login/', views.auth, name="auth"),
    path('', views.home, name="home"),
    path('sign_document/', views.sign_document, name="sign_document"),
    path('submit_pdf_form/', views.submit_pdf_form, name="submit_pdf_form"),
]

user/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


def extension_validate(value):
    if not value.name.endswith(".pdf"):
        raise ValidationError("Invalid File Format!")


class SamplePDFCollections(Base):
    file = models.FileField(upload_to='sample_pdf_collections', validators=[extension_validate])


def get_user_details_document_template_path(instance, file_name):
    return f"Document/{instance.user.username}/DocumentTemplate/{file_name}"


def get_user_details_document_path(instance, file_name):
    return f"Document/{instance.user.username}/{file_name}"


class UserDetails(Base):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    document_template = models.FileField(upload_to=get_user_details_document_template_path)
    document = models.FileField(upload_to=get_user_details_document_path, blank=True, null=True)
    is_verified = models.BooleanField(default=False)


# signals
@receiver(post_save, sender=User, dispatch_uid="create_user_details")
def create_user_details(sender, instance, **kwargs):
    if not UserDetails.objects.filter(user=instance).exists():
        latest_pdf_template = SamplePDFCollections.objects.last().file
        UserDetails.objects.create(
            user=instance,
            document_template=latest_pdf_template,
        )

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseBadRequest, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib import messages

from user.models import *


# Create your views here.


def auth(request):
    if request.method == "POST":
        try:
            username, password = request.POST["username"], request.POST["password"]
            user = authenticate(username=username, password=password)
            if not user:
                raise Exception("Invalid username or password")
            login(request, user)
            messages.success(request, "Login Successful")
            return redirect("user:home")

        except Exception as err:
            messages.error(request, str(err), extra_tags="danger")

    return render(request, "users/auth.html", {})


@login_required
def home(request):
    return render(request, "users/home.html", {"user_details": request.user.userdetails})


@login_required
def sign_document(request):
    user_details = request.user.userdetails
    initial_doc = user_details.document_template if not user_details.document else user_details.document
    return render(request, "users/sign_document.html", {"initialDoc": initial_doc})


@csrf_exempt
@login_required
def submit_pdf_form(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax and request.method == "POST":
        response = {
            "status": 201,
            "message": "Created"
        }
        try:
            document = request.FILES["file"]
            user_details = UserDetails.objects.get(user=request.user)
            user_details.document = document
            user_details.save()
        except Exception as err:
            print(err)
            response["message"] = str(err)
            response["status"] = 400

        return JsonResponse(response, status=response["status"])
    else:
        return HttpResponseBadRequest('Invalid request')

user/templates/users/auth.html
{% extends 'users/base.html' %}
{% block content %}
<div class="container d-flex align-items-center justify-content-center">
    <div class="card mt-5" style="width: 18rem;">
        <div class="card-body">
            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home"
                            type="button" role="tab" aria-controls="pills-home" aria-selected="true">Login
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile"
                            type="button" role="tab" aria-controls="pills-profile" aria-selected="false">SignUp
                    </button>
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                    <form method="POST" action="{% url 'user:auth' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                <input type="text" class="form-control" name="username" placeholder="username" required>
                            </div>
                            <div class="col-12 my-2">
                                <input type="password" class="form-control"  name="password" placeholder="password" required>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-success w-100">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                <input type="text" class="form-control" placeholder="username" required>
                            </div>
                            <div class="col-12 my-2">
                                <input type="password" class="form-control" placeholder="password" required>
                            </div>
                            <div class="col-12">
                                <input type="password" class="form-control" placeholder="re enter password" required>
                            </div>
                            <div class="col-12 mt-2">
                                <button type="submit" class="btn btn-success w-100">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
    
        </div>
    </div>
</div>

{% endblock content %}

user/templates/users/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block head %}
    {% endblock head %}
</head>

<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img style="width: 4vw;" src="https://png.pngtree.com/png-clipart/20220612/original/pngtree-pdf-file-icon-png-png-image_7965915.png" /></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li>
              </ul>
              <form class="d-flex mt-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </div>
      </nav>
{% if messages %}
{% for message in messages %}
<div class="dj_messages alert alert-{{message.tags}}" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}


{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

{% block scripts %}
{% endblock scripts %}
<script>
    function clearMessageElements(){
        $('.dj_messages').remove();
    }
    const myTimeout = setTimeout(clearMessageElements, 3000);
</script>
</body>
</html>

user/templates/users/home.html
{% extends 'users/base.html' %}

{% block content %}
<div class="container mt-5">
   <h1>Welcome {{request.user.username}}.</h1>

   <a target="_blank" href="{% url 'user:sign_document' %}">{% if not user_details.document %}Please fill your document{% else %}view / edit your document{% endif %} >></a>

</div>

{% endblock content %}

user/templates/users/sign_document.html
{% extends 'users/base.html' %}
{% load static %}
{% block head %}
<style>
  .ActionButton{
    background: #8ecdd7 !important;
    width: 8vw !important;
    filter: drop-shadow(0px 0px 0px black) !important;
  }
</style>
<script src="{% static 'WebViewer/lib/webviewer.min.js' %}"></script>

{% endblock head %}

{% block content %}
<form
    style="display: none;"
    enctype="multipart/form-data"
    id="upload_form" method="POST"
    novalidate="">
    <input type="text" name="fname" value="vivek" />
    <input type="file" name="file" />
</form>
<div id='viewer' style='width: 100%; height: 100vh; margin: 0 auto;'></div>
{% endblock content %}



{% block scripts %}
  <script>
    //submitFORM
    $("#upload_form").submit(function(event){
      event.preventDefault();

      var formData = new FormData($(this)[0]);
      $.ajax({
        enctype : "multipart/form-data",
        url: "{% url 'user:submit_pdf_form' %}",
        data: formData,
        type: "POST",
        dataType: 'json',
        processData: false,
        contentType: false,
        success: function( response )
        {
          if (response.status === 201){
            alert("Success!");
          }
          else{
            alert("Something went wrong!");
            console.error("AJAX SUCCESS - ELSE ", response);
          }
        },
        error: function (response) {console.error(response); }
      })
    });



    WebViewer({
      path: "{% static 'WebViewer/lib' %}",
      licenseKey: 'demo:1705836628496:7f6353e903000000005ca250c1d3d044cf389095014ad981b7a2ad5835',
      initialDoc: '{% get_media_prefix %}{{initialDoc}}',
      disabledElements: [
                'selectToolButton',
                'signatureToolGroupButton',
                'leftPanelButton',
                'ribbons',
                'toggleNotesButton',
                'searchButton',
                'menuButton',
                'rubberStampToolGroupButton',
                'stampToolGroupButton',
                'fileAttachmentToolGroupButton',
                'calloutToolGroupButton',
                'undo',
                'redo',
                'eraserToolButton'
            ],
    }, document.getElementById('viewer'))
    .then(instance => {
        const { documentViewer, annotationManager } = instance.Core;

        documentViewer.addEventListener('documentLoaded', () => {
            console.log("document loaded")
        });

        instance.UI.setHeaderItems(header => {
        header.push({
            type : 'actionButton',
            img : 'https://cdn1.iconfinder.com/data/icons/ios-11-glyphs/30/save-512.png',
            onClick: async () => {


                console.log("inside actionButton")
                const doc = documentViewer.getDocument();
                const xfdfString = await annotationManager.exportAnnotations();
                const data = await doc.getFileData({xfdfString});
                const arr = new Uint8Array(data);
                const blob = new Blob([arr], { type: 'application/pdf' });
                // Add code for handling Blob here

                const blobURL = URL.createObjectURL(blob);
                console.log(blobURL)

                let file = new File([blob], "document.pdf", {type: 'application/pdf'});
                console.log(file)

                const fileInput = document.querySelector('input[type="file"]');

                const dataTransfer = new DataTransfer();
                dataTransfer.items.add(file);
                fileInput.files = dataTransfer.files;


                $("#upload_form").submit()
            }
        });
        });

    });
  </script>
{% endblock scripts %}